### PR TITLE
Add member info for davidwengier

### PR DESCRIPTION
**Pull request by davidwengier**
I typed words about myself. It was hard.

### CODE REVIEW

**Comment by mtheoryx** [comment]
It looks like you've changed your profile image (the extension is changed from jpg to png), but that image doesn't exist in the image/members directory.

Did you mean to leave this as jpg, or doe you have a new image to add to this PR?

**Comment by davidwengier** [comment]
Whips, didn't mean to change it. Will fix it up tomorrow :)

**Comment by davidwengier** [comment]
Fixed the image name. Thanks for picking that up @mtheoryx!

**Comment by mtheoryx** [comment]
Looks great, thanks for fixing that up @davidwengier !

**Pull request merged**
