### PR TITLE
Updates to 1kevgriff (Kevin Griffin)

### PR DESCRIPTION
**Pull request by 1kevgriff**

### CODE REVIEW

**Comment by mtheoryx** [comment]
Thank you for updating your member page!

Something I found with your StackOverflow id... it doesn't appear to work. The field we are expecting is a number portion of your id. For example, mine is:

https://stackoverflow.com/users/7233527/david-r-poindexter-iii

Where `7233527` would be the id number I would enter in my page information (roberttables).

Would you like to try updating that before we merge?

**Comment by 1kevgriff** [comment]
Ah - give me 5 minutes

**Comment by 1kevgriff** [comment]
@mtheoryx How's that?

**Comment by mtheoryx** [comment]
Perfect!

**Pull request merged**
